---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
registries:
  - type: standard
    ref: v4.306.0 # renovate: depName=aquaproj/aqua-registry
packages:
  - name: nektos/act@v0.2.72
  - name: rhysd/actionlint@v1.7.7
  - name: evilmartians/lefthook@v1.10.10
