---
skip_output:
  - meta # Skips lefthook version printing
  - empty_summary # Skips summary heading when there are no steps to run
  - skips # Skips "skip" printing (i.e. no files matched)
pre-commit:
  parallel: true
  commands:
    actionlint:
      tags: lint build
      glob: '.github/workflows/*.yml'
      run: aqua exec -- actionlint {staged_files}
    lint:
      tags: lint
      run: aqua exec -- act pull_request --platform catthehacker/ubuntu:act-latest --action-offline-mode --var SUPERLINTER_RUN_LOCAL="true" --var SUPERLINTER_FIX="true"
